services:
  ocr-pipeline:
    build: .
    container_name: ocr_pipeline
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./output_with_text_layer:/app/output_with_text_layer
      - ./logs:/app/logs
    tty: true
